//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int Id_Admin { get; set; }
        public string Nom { get; set; }
        public string NomUtilisateur { get; set; }
        public string MotPasse { get; set; }
        public bool Autorise { get; set; }
        public string Code_Aeroport { get; set; }
    
        public virtual Administration Administration { get; set; }
    }
}
