//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class aeroportEntities : DbContext
    {
        public aeroportEntities()
            : base("name=aeroportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Administration> Administrations { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Aeroport> Aeroports { get; set; }
        public virtual DbSet<Calendrier> Calendriers { get; set; }
        public virtual DbSet<CompagniesAerienne> CompagniesAeriennes { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Ville> Villes { get; set; }
        public virtual DbSet<Vol> Vols { get; set; }
        public virtual DbSet<VolsCedule> VolsCedules { get; set; }
        public virtual DbSet<Notification1> Notifications1 { get; set; }
        public virtual DbSet<View_1> View_1 { get; set; }
        public virtual DbSet<VOLS_ARRIVES_Today> VOLS_ARRIVES_Today { get; set; }
        public virtual DbSet<VOLS_ARRIVES_Tomorrow> VOLS_ARRIVES_Tomorrow { get; set; }
        public virtual DbSet<VOLS_DEPARTS_Today> VOLS_DEPARTS_Today { get; set; }
        public virtual DbSet<VOLS_DEPARTS_Tomorrow> VOLS_DEPARTS_Tomorrow { get; set; }
        public virtual DbSet<VOLS_RECHERCHES48H> VOLS_RECHERCHES48H { get; set; }
    }
}
