//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public string Num_Phone { get; set; }
        public string Num_Vol { get; set; }
        public System.DateTime Date_Notification { get; set; }
        public bool Statut { get; set; }
        public string Langue { get; set; }
        public Nullable<int> Id_Date_Depart { get; set; }
    }
}
