//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vol
    {
        public string Numero { get; set; }
        public System.TimeSpan Heure_Depart { get; set; }
        public System.TimeSpan Heure_Arrivee { get; set; }
        public int Id_Date_Depart { get; set; }
        public int Id_Date_Arrivee { get; set; }
        public string Code_CompAerien { get; set; }
        public string Code_IATA_Aeroport_Depart { get; set; }
        public string Code_IATA_Aeroport_Arrivee { get; set; }
    
        public virtual Aeroport Aeroport { get; set; }
        public virtual Aeroport Aeroport1 { get; set; }
        public virtual Calendrier Calendrier { get; set; }
        public virtual Calendrier Calendrier1 { get; set; }
        public virtual CompagniesAerienne CompagniesAerienne { get; set; }
        public virtual VolsCedule VolsCedule { get; set; }
    }
}
