//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolsCedule
    {
        public string Numero_Vol { get; set; }
        public Nullable<System.DateTime> Date_Depart_Revisee { get; set; }
        public Nullable<System.DateTime> Date_Arrivee_Revisee { get; set; }
        public string Statut { get; set; }
        public string Etat { get; set; }
        public System.DateTime Date_MAJ { get; set; }
        public int Id_Date_Depart { get; set; }
    
        public virtual Vol Vol { get; set; }

        public Boolean IsEqual(VolsCedule vol)
        {

            if(this.Statut != vol.Statut || 
                this.Etat != vol.Etat || 
                this.Date_Arrivee_Revisee != vol.Date_Arrivee_Revisee||
                this.Date_Depart_Revisee != vol.Date_Depart_Revisee)
            {
                return false;
            }

            return true;
        }
    }
}
